name: Software test, formatting & publishing

on:
  push:
    paths:
      - 'src/lavague/**.py'
      - '.github/setup-driver.sh'
      - 'examples/configurations/**'
      - 'examples/instructions/**'

jobs:
  lint:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff on src/lavague
      run: ruff format src/lavague/
    
    - name: Run Ruff on examples
      run: ruff format examples/


  test:
    name: Run Installation and Tests
    runs-on: ubuntu-latest
    needs: lint  

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install necessary dependencies
      run: |
        pip install -e '.[playwright]'
        playwright install chromium

    - name: Run selenium test
      run: lavague -c examples/test-configurations/test_selenium.py -i examples/instructions/hackernews.yaml test
    
    - name: Run playwright test
      run: lavague -c examples/test-configurations/test_playwright.py -i examples/instructions/hackernews.yaml test

    - name: Execute Generated Python Scripts
      run: python hackernews_test_selenium_gen.py && python hackernews_test_playwright_gen.py

    - name: Check Execution Status
      if: ${{ failure() }}
      run: echo "Script execution failed" && exit 1

  publish:
    name: Push on PyPI
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install twine & build
      run: >-
        python3 -m
        pip install
        twine build
        --user

    - name: Build the wheel and the source tarball
      run: python3 -m build

    - name: Publish to github
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: twine upload dist/*

  check-docs-with-new-package:
    runs-on: ubuntu-latest
    needs: publish
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Sleep to ensure package is updated
      run: sleep 30

    - name: Install Python dependencies and nbconvert
      run: pip install notebook nbconvert lavague

    - name: Execute the notebook
      run: |
          jupyter nbconvert --to notebook --execute --inplace --output executed_notebook.ipynb docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb

    - name: Extract Python code from README.md
      run: |
        sed -n '/```python/,/```/p' README.md | sed '/```*/d' > check-code.py

    - name: Check code consistency with docs/index.md
      run: |
        if ! diff -wu <(sed -n '/```python/,/```/p' README.md | sed '/```*/d') <(sed -n '/```python/,/```/p' docs/index.md | sed '/```*/d'); then
          echo "The Python code blocks in README.md and docs/index.md do not match."
          exit 1
        fi

    - name: Run the Python script
      run: |
        python check-code.py

  notify:
    runs-on: ubuntu-latest
    needs: [  check-docs-with-new-package ]
    if: ${{ failure() || needs.check-docs-with-new-package.outcome == 'failure' }}
    steps:
      - name: Send failure notification via Discord
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "The code in the README fails or differs from the code on docs home - please fix!"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DOCS_DISCORD_WEBHOOK }}
