name: spellcheck & README link checker
on:
  push:
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pyspelling

      - name: Install Aspell
        run: |
        sudo apt-get install aspell aspell-en

      - name: Spellcheck Markdown files
        run: |
          pyspelling -c .github/.pyspelling.yaml
  
  check-README-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check links in README.md
        run: markdown-link-check README.md
  
  notify:
    runs-on: ubuntu-latest
    needs: check-README-links
    if: ${{ failure() || needs.check-README-links.outcome == 'failure' }}
    steps:
      - name: Send failure notification via Discord
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "The link check failed, please review."
        env:
          DISCORD_WEBHOOK: ${{ secrets.DOCS_DISCORD_WEBHOOK }}
