name: Python Code Check in docs and README

on:
  push:
    paths:
      - 'lavague-core/**'
      - 'lavague-integrations/**'
      - '_lavague/**'
      - 'lavague-gradio/**'
      - 'pyproject.toml'
      - '.github/workflows/docs-code.yaml'
    
jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Extract Python code from README.md
      # Remove headless=False if it is present
      run: |
        sed -n '/```python/,/```/p' README.md | sed '/```*/d' | sed 's/headless=False//g' > check-code.py

    - name: Install dependencies
      run: |
        pip install -e .

    - name: Check code consistency with docs/index.md
      run: |
        if ! diff -wu <(sed -n '/```python/,/```/p' README.md | sed '/```*/d') <(sed -n '/```python/,/```/p' docs/index.md | sed '/```*/d'); then
          echo "The Python code blocks in README.md and docs/index.md do not match."
          exit 1
        fi

    - name: Run the Python script
      run: |
        python check-code.py
    
  execute-notebook:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' 

    - name: Install Python dependencies and nbconvert
      run: pip install notebook nbconvert lavague

    - name: Execute the notebook
      run: jupyter nbconvert --to notebook --execute --inplace --output executed_notebook.ipynb docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb