name: Check Links
on:
  push:
    paths:
      - 'docs/**' # Trigger if there are changes within the /docs directory
  schedule:
    - cron: "*/10 * * * *" # run 10 minutes after push so docs have time to build

jobs:
  check-links:
    if: github.event_name == 'schedule' # Only run if triggered by a schedule event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y linkchecker

      - name: Check links
        id: linkcheck
        run: linkchecker https://docs.lavague.ai/en/latest/
  
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pyspelling

      - name: Spellcheck Markdown files
        run: |
          pyspelling -c .github/.pyspelling.yaml
  
  notify:
    runs-on: ubuntu-latest
    needs: check-links
    if: ${{ failure() }}
    steps:
      - name: Send failure notification via Discord
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "The link check failed, please review."
        env:
          DISCORD_WEBHOOK: ${{ secrets.DOCS_DISCORD_WEBHOOK }}