name: Execute Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:


  notify:
    runs-on: ubuntu-latest
    needs: [ execute-notebook ]
    if: ${{ failure() || needs.execute-notebook.outcome == 'failure' }}
    steps:
      - name: Send failure notification via Discord
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "The code in the README fails or differs from the code on docs home - please fix!"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DOCS_DISCORD_WEBHOOK }}